# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'HDMI_Chauffage.ui'
#
# Created by: PyQt4 UI code generator 4.12.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName(_fromUtf8("Dialog"))
        Dialog.resize(424, 459)
        self.tabWidget = QtGui.QTabWidget(Dialog)
        self.tabWidget.setGeometry(QtCore.QRect(0, 10, 421, 381))
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab1 = QtGui.QWidget()
        self.tab1.setObjectName(_fromUtf8("tab1"))
        self.groupBox = QtGui.QGroupBox(self.tab1)
        self.groupBox.setGeometry(QtCore.QRect(10, 10, 391, 141))
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.label = QtGui.QLabel(self.groupBox)
        self.label.setGeometry(QtCore.QRect(30, 30, 71, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label.setObjectName(_fromUtf8("label"))
        self.label_2 = QtGui.QLabel(self.groupBox)
        self.label_2.setGeometry(QtCore.QRect(150, 30, 91, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.label_3 = QtGui.QLabel(self.groupBox)
        self.label_3.setGeometry(QtCore.QRect(150, 70, 91, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_3.setFont(font)
        self.label_3.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.label_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.lcdNumber_3 = QtGui.QLCDNumber(self.groupBox)
        self.lcdNumber_3.setGeometry(QtCore.QRect(250, 60, 81, 31))
        self.lcdNumber_3.setStyleSheet(_fromUtf8("color: rgb(0, 0, 255);\n"
"background-color: rgb(237, 255, 240)"))
        self.lcdNumber_3.setSmallDecimalPoint(True)
        self.lcdNumber_3.setSegmentStyle(QtGui.QLCDNumber.Flat)
        self.lcdNumber_3.setObjectName(_fromUtf8("lcdNumber_3"))
        self.lcdNumber_2 = QtGui.QLCDNumber(self.groupBox)
        self.lcdNumber_2.setGeometry(QtCore.QRect(250, 20, 81, 31))
        self.lcdNumber_2.setStyleSheet(_fromUtf8("color: rgb(0, 0, 255);\n"
"background-color: rgb(237, 255, 240)"))
        self.lcdNumber_2.setSmallDecimalPoint(True)
        self.lcdNumber_2.setSegmentStyle(QtGui.QLCDNumber.Flat)
        self.lcdNumber_2.setProperty("value", 0.0)
        self.lcdNumber_2.setObjectName(_fromUtf8("lcdNumber_2"))
        self.lcdNumber_4 = QtGui.QLCDNumber(self.groupBox)
        self.lcdNumber_4.setGeometry(QtCore.QRect(250, 100, 81, 31))
        self.lcdNumber_4.setStyleSheet(_fromUtf8("color: rgb(0, 0, 255);\n"
"background-color: rgb(237, 255, 240)\n"
""))
        self.lcdNumber_4.setLineWidth(1)
        self.lcdNumber_4.setSmallDecimalPoint(True)
        self.lcdNumber_4.setSegmentStyle(QtGui.QLCDNumber.Flat)
        self.lcdNumber_4.setObjectName(_fromUtf8("lcdNumber_4"))
        self.label_4 = QtGui.QLabel(self.groupBox)
        self.label_4.setGeometry(QtCore.QRect(150, 110, 91, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_4.setFont(font)
        self.label_4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.label_5 = QtGui.QLabel(self.groupBox)
        self.label_5.setGeometry(QtCore.QRect(340, 30, 21, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_5.setFont(font)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.label_6 = QtGui.QLabel(self.groupBox)
        self.label_6.setGeometry(QtCore.QRect(340, 70, 21, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_6.setFont(font)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.label_7 = QtGui.QLabel(self.groupBox)
        self.label_7.setGeometry(QtCore.QRect(340, 110, 21, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_7.setFont(font)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.label_8 = QtGui.QLabel(self.groupBox)
        self.label_8.setGeometry(QtCore.QRect(110, 70, 21, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_8.setFont(font)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.lineEdit = QtGui.QLineEdit(self.groupBox)
        self.lineEdit.setGeometry(QtCore.QRect(30, 60, 71, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.lineEdit.setFont(font)
        self.lineEdit.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.lineEdit.setStyleSheet(_fromUtf8("color: rgb(255, 0, 0);\n"
"background-color: rgb(237, 255, 240)"))
        self.lineEdit.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.lineEdit.setText(_fromUtf8(""))
        self.lineEdit.setMaxLength(5)
        self.lineEdit.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit.setObjectName(_fromUtf8("lineEdit"))
        self.groupBox_2 = QtGui.QGroupBox(self.tab1)
        self.groupBox_2.setGeometry(QtCore.QRect(10, 150, 391, 161))
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.pushButton = QtGui.QPushButton(self.groupBox_2)
        self.pushButton.setGeometry(QtCore.QRect(10, 20, 91, 31))
        self.pushButton.setStyleSheet(_fromUtf8(""))
        self.pushButton.setText(_fromUtf8("ON/OFF"))
        self.pushButton.setCheckable(False)
        self.pushButton.setObjectName(_fromUtf8("pushButton"))
        self.label_10 = QtGui.QLabel(self.groupBox_2)
        self.label_10.setGeometry(QtCore.QRect(210, 20, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_10.setFont(font)
        self.label_10.setStyleSheet(_fromUtf8("background-color: rgb(255, 0, 0);"))
        self.label_10.setFrameShape(QtGui.QFrame.WinPanel)
        self.label_10.setFrameShadow(QtGui.QFrame.Raised)
        self.label_10.setAlignment(QtCore.Qt.AlignCenter)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.label_11 = QtGui.QLabel(self.groupBox_2)
        self.label_11.setGeometry(QtCore.QRect(0, 60, 101, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_11.setFont(font)
        self.label_11.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.progressBar = QtGui.QProgressBar(self.groupBox_2)
        self.progressBar.setGeometry(QtCore.QRect(110, 60, 271, 16))
        self.progressBar.setProperty("value", 0)
        self.progressBar.setTextVisible(True)
        self.progressBar.setObjectName(_fromUtf8("progressBar"))
        self.label_30 = QtGui.QLabel(self.groupBox_2)
        self.label_30.setGeometry(QtCore.QRect(60, 90, 151, 21))
        self.label_30.setStyleSheet(_fromUtf8("font: 10pt \"Sans Serif\";"))
        self.label_30.setObjectName(_fromUtf8("label_30"))
        self.label_31 = QtGui.QLabel(self.groupBox_2)
        self.label_31.setGeometry(QtCore.QRect(330, 90, 41, 21))
        self.label_31.setStyleSheet(_fromUtf8("font: 12pt \"Sans Serif\";"))
        self.label_31.setObjectName(_fromUtf8("label_31"))
        self.lcdNumber_12 = QtGui.QLCDNumber(self.groupBox_2)
        self.lcdNumber_12.setGeometry(QtCore.QRect(210, 80, 111, 31))
        self.lcdNumber_12.setStyleSheet(_fromUtf8("background-color: rgb(220, 251, 255);\n"
"color: rgb(0, 0, 127);"))
        self.lcdNumber_12.setSmallDecimalPoint(True)
        self.lcdNumber_12.setNumDigits(7)
        self.lcdNumber_12.setSegmentStyle(QtGui.QLCDNumber.Flat)
        self.lcdNumber_12.setProperty("intValue", 0)
        self.lcdNumber_12.setObjectName(_fromUtf8("lcdNumber_12"))
        self.lcdNumber_13 = QtGui.QLCDNumber(self.groupBox_2)
        self.lcdNumber_13.setGeometry(QtCore.QRect(210, 120, 111, 31))
        self.lcdNumber_13.setStyleSheet(_fromUtf8("background-color: rgb(220, 251, 255);\n"
"color: rgb(0, 0, 127);"))
        self.lcdNumber_13.setSmallDecimalPoint(True)
        self.lcdNumber_13.setNumDigits(7)
        self.lcdNumber_13.setSegmentStyle(QtGui.QLCDNumber.Flat)
        self.lcdNumber_13.setProperty("intValue", 0)
        self.lcdNumber_13.setObjectName(_fromUtf8("lcdNumber_13"))
        self.label_32 = QtGui.QLabel(self.groupBox_2)
        self.label_32.setGeometry(QtCore.QRect(60, 130, 151, 21))
        self.label_32.setStyleSheet(_fromUtf8("font: 10pt \"Sans Serif\";"))
        self.label_32.setObjectName(_fromUtf8("label_32"))
        self.label_33 = QtGui.QLabel(self.groupBox_2)
        self.label_33.setGeometry(QtCore.QRect(330, 130, 41, 21))
        self.label_33.setStyleSheet(_fromUtf8("font: 12pt \"Sans Serif\";"))
        self.label_33.setObjectName(_fromUtf8("label_33"))
        self.label_37 = QtGui.QLabel(self.groupBox_2)
        self.label_37.setGeometry(QtCore.QRect(110, 30, 91, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_37.setFont(font)
        self.label_37.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_37.setObjectName(_fromUtf8("label_37"))
        self.label_27 = QtGui.QLabel(self.groupBox_2)
        self.label_27.setGeometry(QtCore.QRect(350, 20, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_27.setFont(font)
        self.label_27.setStyleSheet(_fromUtf8("background-color: rgb(255, 0, 0);"))
        self.label_27.setFrameShape(QtGui.QFrame.WinPanel)
        self.label_27.setFrameShadow(QtGui.QFrame.Raised)
        self.label_27.setAlignment(QtCore.Qt.AlignCenter)
        self.label_27.setObjectName(_fromUtf8("label_27"))
        self.label_51 = QtGui.QLabel(self.groupBox_2)
        self.label_51.setGeometry(QtCore.QRect(250, 30, 91, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_51.setFont(font)
        self.label_51.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_51.setObjectName(_fromUtf8("label_51"))
        self.tabWidget.addTab(self.tab1, _fromUtf8(""))
        self.tab2 = QtGui.QWidget()
        self.tab2.setObjectName(_fromUtf8("tab2"))
        self.groupBox_3 = QtGui.QGroupBox(self.tab2)
        self.groupBox_3.setGeometry(QtCore.QRect(10, 10, 391, 171))
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.lcdNumber = QtGui.QLCDNumber(self.groupBox_3)
        self.lcdNumber.setGeometry(QtCore.QRect(190, 10, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.lcdNumber.setFont(font)
        self.lcdNumber.setStyleSheet(_fromUtf8("background-color: rgb(220, 251, 255);\n"
"color: rgb(250, 0, 255);"))
        self.lcdNumber.setSmallDecimalPoint(False)
        self.lcdNumber.setNumDigits(8)
        self.lcdNumber.setSegmentStyle(QtGui.QLCDNumber.Flat)
        self.lcdNumber.setProperty("intValue", 0)
        self.lcdNumber.setObjectName(_fromUtf8("lcdNumber"))
        self.lcdNumber_5 = QtGui.QLCDNumber(self.groupBox_3)
        self.lcdNumber_5.setGeometry(QtCore.QRect(190, 40, 111, 31))
        self.lcdNumber_5.setStyleSheet(_fromUtf8("background-color: rgb(220, 251, 255);\n"
"font: 9pt \"Sans Serif\";\n"
"color: rgb(250, 0, 255);"))
        self.lcdNumber_5.setSmallDecimalPoint(False)
        self.lcdNumber_5.setNumDigits(8)
        self.lcdNumber_5.setSegmentStyle(QtGui.QLCDNumber.Flat)
        self.lcdNumber_5.setProperty("intValue", 0)
        self.lcdNumber_5.setObjectName(_fromUtf8("lcdNumber_5"))
        self.label_9 = QtGui.QLabel(self.groupBox_3)
        self.label_9.setGeometry(QtCore.QRect(310, 20, 31, 21))
        self.label_9.setStyleSheet(_fromUtf8("font: 12pt \"Sans Serif\";"))
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.label_13 = QtGui.QLabel(self.groupBox_3)
        self.label_13.setGeometry(QtCore.QRect(310, 50, 31, 21))
        self.label_13.setStyleSheet(_fromUtf8("font: 12pt \"Sans Serif\";"))
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.label_14 = QtGui.QLabel(self.groupBox_3)
        self.label_14.setGeometry(QtCore.QRect(40, 20, 141, 21))
        self.label_14.setStyleSheet(_fromUtf8("font: 10pt \"Sans Serif\";"))
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.label_15 = QtGui.QLabel(self.groupBox_3)
        self.label_15.setGeometry(QtCore.QRect(40, 50, 141, 21))
        self.label_15.setStyleSheet(_fromUtf8("font: 10pt \"Sans Serif\";"))
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.label_16 = QtGui.QLabel(self.groupBox_3)
        self.label_16.setGeometry(QtCore.QRect(40, 110, 61, 21))
        self.label_16.setStyleSheet(_fromUtf8("font: 10pt \"Sans Serif\";"))
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.label_17 = QtGui.QLabel(self.groupBox_3)
        self.label_17.setGeometry(QtCore.QRect(40, 80, 151, 21))
        self.label_17.setStyleSheet(_fromUtf8("font: 10pt \"Sans Serif\";"))
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.lcdNumber_6 = QtGui.QLCDNumber(self.groupBox_3)
        self.lcdNumber_6.setGeometry(QtCore.QRect(190, 100, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.lcdNumber_6.setFont(font)
        self.lcdNumber_6.setStyleSheet(_fromUtf8("background-color: rgb(220, 251, 255);\n"
"color: rgb(250, 0, 255);"))
        self.lcdNumber_6.setSmallDecimalPoint(False)
        self.lcdNumber_6.setNumDigits(8)
        self.lcdNumber_6.setSegmentStyle(QtGui.QLCDNumber.Flat)
        self.lcdNumber_6.setProperty("value", 0.0)
        self.lcdNumber_6.setProperty("intValue", 0)
        self.lcdNumber_6.setObjectName(_fromUtf8("lcdNumber_6"))
        self.label_18 = QtGui.QLabel(self.groupBox_3)
        self.label_18.setGeometry(QtCore.QRect(310, 110, 31, 21))
        self.label_18.setStyleSheet(_fromUtf8("font: 12pt \"Sans Serif\";"))
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.lcdNumber_7 = QtGui.QLCDNumber(self.groupBox_3)
        self.lcdNumber_7.setGeometry(QtCore.QRect(190, 70, 111, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Sans Serif"))
        font.setPointSize(9)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        self.lcdNumber_7.setFont(font)
        self.lcdNumber_7.setStyleSheet(_fromUtf8("background-color: rgb(220, 251, 255);\n"
"font: 9pt \"Sans Serif\";\n"
"color: rgb(250, 0, 255);"))
        self.lcdNumber_7.setSmallDecimalPoint(False)
        self.lcdNumber_7.setNumDigits(8)
        self.lcdNumber_7.setSegmentStyle(QtGui.QLCDNumber.Flat)
        self.lcdNumber_7.setProperty("intValue", 0)
        self.lcdNumber_7.setObjectName(_fromUtf8("lcdNumber_7"))
        self.label_19 = QtGui.QLabel(self.groupBox_3)
        self.label_19.setGeometry(QtCore.QRect(310, 80, 31, 21))
        self.label_19.setStyleSheet(_fromUtf8("font: 12pt \"Sans Serif\";"))
        self.label_19.setObjectName(_fromUtf8("label_19"))
        self.label_34 = QtGui.QLabel(self.groupBox_3)
        self.label_34.setGeometry(QtCore.QRect(40, 140, 101, 21))
        self.label_34.setStyleSheet(_fromUtf8("font: 10pt \"Sans Serif\";"))
        self.label_34.setObjectName(_fromUtf8("label_34"))
        self.label_35 = QtGui.QLabel(self.groupBox_3)
        self.label_35.setGeometry(QtCore.QRect(220, 140, 81, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Sans Serif"))
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_35.setFont(font)
        self.label_35.setStyleSheet(_fromUtf8("font: 14pt \"Sans Serif\";\n"
"background-color: rgb(170, 170, 255);"))
        self.label_35.setFrameShape(QtGui.QFrame.Box)
        self.label_35.setAlignment(QtCore.Qt.AlignCenter)
        self.label_35.setObjectName(_fromUtf8("label_35"))
        self.tabWidget.addTab(self.tab2, _fromUtf8(""))
        self.tab3 = QtGui.QWidget()
        self.tab3.setObjectName(_fromUtf8("tab3"))
        self.groupBox_4 = QtGui.QGroupBox(self.tab3)
        self.groupBox_4.setGeometry(QtCore.QRect(10, 10, 391, 141))
        self.groupBox_4.setObjectName(_fromUtf8("groupBox_4"))
        self.label_25 = QtGui.QLabel(self.groupBox_4)
        self.label_25.setGeometry(QtCore.QRect(340, 80, 21, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_25.setFont(font)
        self.label_25.setObjectName(_fromUtf8("label_25"))
        self.label_26 = QtGui.QLabel(self.groupBox_4)
        self.label_26.setGeometry(QtCore.QRect(130, 80, 111, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_26.setFont(font)
        self.label_26.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_26.setObjectName(_fromUtf8("label_26"))
        self.lcdNumber_11 = QtGui.QLCDNumber(self.groupBox_4)
        self.lcdNumber_11.setGeometry(QtCore.QRect(250, 70, 81, 31))
        self.lcdNumber_11.setStyleSheet(_fromUtf8("color: rgb(0, 0, 255);\n"
"background-color: rgb(237, 255, 240)"))
        self.lcdNumber_11.setSmallDecimalPoint(True)
        self.lcdNumber_11.setSegmentStyle(QtGui.QLCDNumber.Flat)
        self.lcdNumber_11.setProperty("value", 0.0)
        self.lcdNumber_11.setObjectName(_fromUtf8("lcdNumber_11"))
        self.progressBar_3 = QtGui.QProgressBar(self.groupBox_4)
        self.progressBar_3.setGeometry(QtCore.QRect(130, 110, 261, 16))
        self.progressBar_3.setMaximum(100)
        self.progressBar_3.setProperty("value", 0)
        self.progressBar_3.setTextVisible(True)
        self.progressBar_3.setObjectName(_fromUtf8("progressBar_3"))
        self.label_24 = QtGui.QLabel(self.groupBox_4)
        self.label_24.setGeometry(QtCore.QRect(0, 110, 121, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_24.setFont(font)
        self.label_24.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_24.setObjectName(_fromUtf8("label_24"))
        self.label_21 = QtGui.QLabel(self.groupBox_4)
        self.label_21.setGeometry(QtCore.QRect(130, 40, 111, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_21.setFont(font)
        self.label_21.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_21.setObjectName(_fromUtf8("label_21"))
        self.lcdNumber_8 = QtGui.QLCDNumber(self.groupBox_4)
        self.lcdNumber_8.setGeometry(QtCore.QRect(250, 30, 81, 31))
        self.lcdNumber_8.setStyleSheet(_fromUtf8("color: rgb(0, 0, 255);\n"
"background-color: rgb(237, 255, 240)"))
        self.lcdNumber_8.setSmallDecimalPoint(True)
        self.lcdNumber_8.setSegmentStyle(QtGui.QLCDNumber.Flat)
        self.lcdNumber_8.setProperty("value", 0.0)
        self.lcdNumber_8.setObjectName(_fromUtf8("lcdNumber_8"))
        self.label_20 = QtGui.QLabel(self.groupBox_4)
        self.label_20.setGeometry(QtCore.QRect(340, 40, 21, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_20.setFont(font)
        self.label_20.setObjectName(_fromUtf8("label_20"))
        self.groupBox_5 = QtGui.QGroupBox(self.tab3)
        self.groupBox_5.setGeometry(QtCore.QRect(10, 160, 391, 101))
        self.groupBox_5.setObjectName(_fromUtf8("groupBox_5"))
        self.label_22 = QtGui.QLabel(self.groupBox_5)
        self.label_22.setGeometry(QtCore.QRect(340, 30, 21, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_22.setFont(font)
        self.label_22.setObjectName(_fromUtf8("label_22"))
        self.label_23 = QtGui.QLabel(self.groupBox_5)
        self.label_23.setGeometry(QtCore.QRect(110, 30, 131, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_23.setFont(font)
        self.label_23.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_23.setObjectName(_fromUtf8("label_23"))
        self.lcdNumber_9 = QtGui.QLCDNumber(self.groupBox_5)
        self.lcdNumber_9.setGeometry(QtCore.QRect(250, 20, 81, 31))
        self.lcdNumber_9.setStyleSheet(_fromUtf8("color: rgb(0, 0, 255);\n"
"background-color: rgb(237, 255, 240)"))
        self.lcdNumber_9.setSmallDecimalPoint(True)
        self.lcdNumber_9.setSegmentStyle(QtGui.QLCDNumber.Flat)
        self.lcdNumber_9.setProperty("value", 0.0)
        self.lcdNumber_9.setObjectName(_fromUtf8("lcdNumber_9"))
        self.label_12 = QtGui.QLabel(self.groupBox_5)
        self.label_12.setGeometry(QtCore.QRect(140, 70, 101, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_12.setFont(font)
        self.label_12.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.progressBar_2 = QtGui.QProgressBar(self.groupBox_5)
        self.progressBar_2.setGeometry(QtCore.QRect(250, 70, 131, 23))
        self.progressBar_2.setMaximum(6000)
        self.progressBar_2.setProperty("value", 0)
        self.progressBar_2.setTextVisible(True)
        self.progressBar_2.setObjectName(_fromUtf8("progressBar_2"))
        self.tabWidget.addTab(self.tab3, _fromUtf8(""))
        self.tab4 = QtGui.QWidget()
        self.tab4.setObjectName(_fromUtf8("tab4"))
        self.groupBox_9 = QtGui.QGroupBox(self.tab4)
        self.groupBox_9.setGeometry(QtCore.QRect(200, 160, 201, 111))
        self.groupBox_9.setObjectName(_fromUtf8("groupBox_9"))
        self.label_56 = QtGui.QLabel(self.groupBox_9)
        self.label_56.setGeometry(QtCore.QRect(0, 70, 71, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_56.setFont(font)
        self.label_56.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.label_56.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_56.setObjectName(_fromUtf8("label_56"))
        self.lcdNumber_23 = QtGui.QLCDNumber(self.groupBox_9)
        self.lcdNumber_23.setGeometry(QtCore.QRect(80, 60, 81, 31))
        self.lcdNumber_23.setStyleSheet(_fromUtf8("color: rgb(0, 0, 255);\n"
"background-color: rgb(237, 255, 240)"))
        self.lcdNumber_23.setSmallDecimalPoint(True)
        self.lcdNumber_23.setSegmentStyle(QtGui.QLCDNumber.Flat)
        self.lcdNumber_23.setObjectName(_fromUtf8("lcdNumber_23"))
        self.label_58 = QtGui.QLabel(self.groupBox_9)
        self.label_58.setGeometry(QtCore.QRect(170, 70, 41, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_58.setFont(font)
        self.label_58.setObjectName(_fromUtf8("label_58"))
        self.label_52 = QtGui.QLabel(self.groupBox_9)
        self.label_52.setGeometry(QtCore.QRect(170, 30, 31, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_52.setFont(font)
        self.label_52.setObjectName(_fromUtf8("label_52"))
        self.lcdNumber_20 = QtGui.QLCDNumber(self.groupBox_9)
        self.lcdNumber_20.setGeometry(QtCore.QRect(80, 20, 81, 31))
        self.lcdNumber_20.setStyleSheet(_fromUtf8("color: rgb(0, 0, 255);\n"
"background-color: rgb(237, 255, 240)"))
        self.lcdNumber_20.setSmallDecimalPoint(True)
        self.lcdNumber_20.setSegmentStyle(QtGui.QLCDNumber.Flat)
        self.lcdNumber_20.setObjectName(_fromUtf8("lcdNumber_20"))
        self.label_50 = QtGui.QLabel(self.groupBox_9)
        self.label_50.setGeometry(QtCore.QRect(0, 30, 71, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_50.setFont(font)
        self.label_50.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.label_50.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_50.setObjectName(_fromUtf8("label_50"))
        self.groupBox_6 = QtGui.QGroupBox(self.tab4)
        self.groupBox_6.setGeometry(QtCore.QRect(10, 10, 181, 141))
        self.groupBox_6.setObjectName(_fromUtf8("groupBox_6"))
        self.label_38 = QtGui.QLabel(self.groupBox_6)
        self.label_38.setGeometry(QtCore.QRect(0, 70, 51, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_38.setFont(font)
        self.label_38.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.label_38.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_38.setObjectName(_fromUtf8("label_38"))
        self.lcdNumber_14 = QtGui.QLCDNumber(self.groupBox_6)
        self.lcdNumber_14.setGeometry(QtCore.QRect(60, 60, 81, 31))
        self.lcdNumber_14.setStyleSheet(_fromUtf8("color: rgb(0, 0, 255);\n"
"background-color: rgb(237, 255, 240)"))
        self.lcdNumber_14.setSmallDecimalPoint(True)
        self.lcdNumber_14.setSegmentStyle(QtGui.QLCDNumber.Flat)
        self.lcdNumber_14.setObjectName(_fromUtf8("lcdNumber_14"))
        self.lcdNumber_16 = QtGui.QLCDNumber(self.groupBox_6)
        self.lcdNumber_16.setGeometry(QtCore.QRect(60, 100, 81, 31))
        self.lcdNumber_16.setStyleSheet(_fromUtf8("color: rgb(0, 0, 255);\n"
"background-color: rgb(237, 255, 240)\n"
""))
        self.lcdNumber_16.setLineWidth(1)
        self.lcdNumber_16.setSmallDecimalPoint(True)
        self.lcdNumber_16.setSegmentStyle(QtGui.QLCDNumber.Flat)
        self.lcdNumber_16.setObjectName(_fromUtf8("lcdNumber_16"))
        self.label_39 = QtGui.QLabel(self.groupBox_6)
        self.label_39.setGeometry(QtCore.QRect(10, 110, 41, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_39.setFont(font)
        self.label_39.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_39.setObjectName(_fromUtf8("label_39"))
        self.label_41 = QtGui.QLabel(self.groupBox_6)
        self.label_41.setGeometry(QtCore.QRect(150, 70, 21, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_41.setFont(font)
        self.label_41.setObjectName(_fromUtf8("label_41"))
        self.label_42 = QtGui.QLabel(self.groupBox_6)
        self.label_42.setGeometry(QtCore.QRect(150, 110, 21, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_42.setFont(font)
        self.label_42.setObjectName(_fromUtf8("label_42"))
        self.label_43 = QtGui.QLabel(self.groupBox_6)
        self.label_43.setGeometry(QtCore.QRect(150, 30, 21, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_43.setFont(font)
        self.label_43.setObjectName(_fromUtf8("label_43"))
        self.lcdNumber_17 = QtGui.QLCDNumber(self.groupBox_6)
        self.lcdNumber_17.setGeometry(QtCore.QRect(60, 20, 81, 31))
        self.lcdNumber_17.setStyleSheet(_fromUtf8("color: rgb(0, 0, 255);\n"
"background-color: rgb(237, 255, 240)"))
        self.lcdNumber_17.setLineWidth(1)
        self.lcdNumber_17.setSmallDecimalPoint(True)
        self.lcdNumber_17.setSegmentStyle(QtGui.QLCDNumber.Flat)
        self.lcdNumber_17.setProperty("value", 0.0)
        self.lcdNumber_17.setProperty("intValue", 0)
        self.lcdNumber_17.setObjectName(_fromUtf8("lcdNumber_17"))
        self.label_44 = QtGui.QLabel(self.groupBox_6)
        self.label_44.setGeometry(QtCore.QRect(10, 30, 41, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_44.setFont(font)
        self.label_44.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_44.setObjectName(_fromUtf8("label_44"))
        self.groupBox_8 = QtGui.QGroupBox(self.tab4)
        self.groupBox_8.setGeometry(QtCore.QRect(10, 160, 181, 111))
        self.groupBox_8.setObjectName(_fromUtf8("groupBox_8"))
        self.label_54 = QtGui.QLabel(self.groupBox_8)
        self.label_54.setGeometry(QtCore.QRect(150, 30, 31, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_54.setFont(font)
        self.label_54.setObjectName(_fromUtf8("label_54"))
        self.lcdNumber_22 = QtGui.QLCDNumber(self.groupBox_8)
        self.lcdNumber_22.setGeometry(QtCore.QRect(60, 20, 81, 31))
        self.lcdNumber_22.setStyleSheet(_fromUtf8("color: rgb(0, 0, 255);\n"
"background-color: rgb(237, 255, 240)"))
        self.lcdNumber_22.setSmallDecimalPoint(True)
        self.lcdNumber_22.setSegmentStyle(QtGui.QLCDNumber.Flat)
        self.lcdNumber_22.setProperty("value", 0.0)
        self.lcdNumber_22.setObjectName(_fromUtf8("lcdNumber_22"))
        self.label_55 = QtGui.QLabel(self.groupBox_8)
        self.label_55.setGeometry(QtCore.QRect(10, 30, 41, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_55.setFont(font)
        self.label_55.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_55.setObjectName(_fromUtf8("label_55"))
        self.label_36 = QtGui.QLabel(self.groupBox_8)
        self.label_36.setGeometry(QtCore.QRect(110, 60, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_36.setFont(font)
        self.label_36.setStyleSheet(_fromUtf8("background-color: rgb(255, 0, 0);"))
        self.label_36.setFrameShape(QtGui.QFrame.WinPanel)
        self.label_36.setFrameShadow(QtGui.QFrame.Raised)
        self.label_36.setAlignment(QtCore.Qt.AlignCenter)
        self.label_36.setObjectName(_fromUtf8("label_36"))
        self.label_57 = QtGui.QLabel(self.groupBox_8)
        self.label_57.setGeometry(QtCore.QRect(10, 70, 81, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_57.setFont(font)
        self.label_57.setAlignment(QtCore.Qt.AlignCenter)
        self.label_57.setObjectName(_fromUtf8("label_57"))
        self.groupBox_7 = QtGui.QGroupBox(self.tab4)
        self.groupBox_7.setGeometry(QtCore.QRect(200, 10, 201, 141))
        self.groupBox_7.setObjectName(_fromUtf8("groupBox_7"))
        self.label_40 = QtGui.QLabel(self.groupBox_7)
        self.label_40.setGeometry(QtCore.QRect(20, 70, 51, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_40.setFont(font)
        self.label_40.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.label_40.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_40.setObjectName(_fromUtf8("label_40"))
        self.lcdNumber_15 = QtGui.QLCDNumber(self.groupBox_7)
        self.lcdNumber_15.setGeometry(QtCore.QRect(80, 60, 81, 31))
        self.lcdNumber_15.setStyleSheet(_fromUtf8("color: rgb(0, 0, 255);\n"
"background-color: rgb(237, 255, 240)"))
        self.lcdNumber_15.setSmallDecimalPoint(True)
        self.lcdNumber_15.setSegmentStyle(QtGui.QLCDNumber.Flat)
        self.lcdNumber_15.setObjectName(_fromUtf8("lcdNumber_15"))
        self.lcdNumber_18 = QtGui.QLCDNumber(self.groupBox_7)
        self.lcdNumber_18.setGeometry(QtCore.QRect(80, 100, 81, 31))
        self.lcdNumber_18.setStyleSheet(_fromUtf8("color: rgb(0, 0, 255);\n"
"background-color: rgb(237, 255, 240)\n"
""))
        self.lcdNumber_18.setLineWidth(1)
        self.lcdNumber_18.setSmallDecimalPoint(True)
        self.lcdNumber_18.setSegmentStyle(QtGui.QLCDNumber.Flat)
        self.lcdNumber_18.setObjectName(_fromUtf8("lcdNumber_18"))
        self.label_45 = QtGui.QLabel(self.groupBox_7)
        self.label_45.setGeometry(QtCore.QRect(20, 110, 51, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_45.setFont(font)
        self.label_45.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_45.setObjectName(_fromUtf8("label_45"))
        self.label_46 = QtGui.QLabel(self.groupBox_7)
        self.label_46.setGeometry(QtCore.QRect(170, 70, 21, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_46.setFont(font)
        self.label_46.setObjectName(_fromUtf8("label_46"))
        self.label_47 = QtGui.QLabel(self.groupBox_7)
        self.label_47.setGeometry(QtCore.QRect(170, 110, 21, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_47.setFont(font)
        self.label_47.setObjectName(_fromUtf8("label_47"))
        self.label_48 = QtGui.QLabel(self.groupBox_7)
        self.label_48.setGeometry(QtCore.QRect(170, 30, 21, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_48.setFont(font)
        self.label_48.setObjectName(_fromUtf8("label_48"))
        self.lcdNumber_19 = QtGui.QLCDNumber(self.groupBox_7)
        self.lcdNumber_19.setGeometry(QtCore.QRect(80, 20, 81, 31))
        self.lcdNumber_19.setStyleSheet(_fromUtf8("color: rgb(0, 0, 255);\n"
"background-color: rgb(237, 255, 240)"))
        self.lcdNumber_19.setSmallDecimalPoint(True)
        self.lcdNumber_19.setSegmentStyle(QtGui.QLCDNumber.Flat)
        self.lcdNumber_19.setProperty("value", 0.0)
        self.lcdNumber_19.setObjectName(_fromUtf8("lcdNumber_19"))
        self.label_49 = QtGui.QLabel(self.groupBox_7)
        self.label_49.setGeometry(QtCore.QRect(10, 30, 61, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_49.setFont(font)
        self.label_49.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_49.setObjectName(_fromUtf8("label_49"))
        self.tabWidget.addTab(self.tab4, _fromUtf8(""))
        self.label_28 = QtGui.QLabel(Dialog)
        self.label_28.setGeometry(QtCore.QRect(10, 400, 61, 21))
        self.label_28.setAccessibleName(_fromUtf8(""))
        self.label_28.setObjectName(_fromUtf8("label_28"))
        self.label_29 = QtGui.QLabel(Dialog)
        self.label_29.setGeometry(QtCore.QRect(50, 400, 301, 21))
        font = QtGui.QFont()
        font.setItalic(True)
        self.label_29.setFont(font)
        self.label_29.setFrameShape(QtGui.QFrame.NoFrame)
        self.label_29.setTextFormat(QtCore.Qt.RichText)
        self.label_29.setObjectName(_fromUtf8("label_29"))
        self.pushButton_quit = QtGui.QPushButton(Dialog)
        self.pushButton_quit.setGeometry(QtCore.QRect(340, 430, 79, 25))
        self.pushButton_quit.setObjectName(_fromUtf8("pushButton_quit"))
        self.label_53 = QtGui.QLabel(Dialog)
        self.label_53.setGeometry(QtCore.QRect(130, 430, 15, 15))
        self.label_53.setStyleSheet(_fromUtf8("background-color: rgb(233, 225, 255);"))
        self.label_53.setFrameShape(QtGui.QFrame.Panel)
        self.label_53.setText(_fromUtf8(""))
        self.label_53.setObjectName(_fromUtf8("label_53"))
        self.label_59 = QtGui.QLabel(Dialog)
        self.label_59.setGeometry(QtCore.QRect(290, 430, 15, 15))
        self.label_59.setStyleSheet(_fromUtf8("background-color: rgb(233, 225, 255);"))
        self.label_59.setFrameShape(QtGui.QFrame.Panel)
        self.label_59.setText(_fromUtf8(""))
        self.label_59.setObjectName(_fromUtf8("label_59"))
        self.label_60 = QtGui.QLabel(Dialog)
        self.label_60.setGeometry(QtCore.QRect(10, 430, 141, 16))
        self.label_60.setObjectName(_fromUtf8("label_60"))
        self.label_61 = QtGui.QLabel(Dialog)
        self.label_61.setGeometry(QtCore.QRect(190, 430, 91, 16))
        self.label_61.setObjectName(_fromUtf8("label_61"))

        self.retranslateUi(Dialog)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(_translate("Dialog", "Solaire et chauffage", None))
        self.groupBox.setTitle(_translate("Dialog", "Températures", None))
        self.label.setText(_translate("Dialog", "Consigne ", None))
        self.label_2.setText(_translate("Dialog", " Exterieure ", None))
        self.label_3.setText(_translate("Dialog", "Interieur ", None))
        self.label_4.setText(_translate("Dialog", "Ballon solaire", None))
        self.label_5.setText(_translate("Dialog", "°C", None))
        self.label_6.setText(_translate("Dialog", "°C", None))
        self.label_7.setText(_translate("Dialog", "°C", None))
        self.label_8.setText(_translate("Dialog", "°C", None))
        self.groupBox_2.setTitle(_translate("Dialog", "Commande, etat", None))
        self.label_10.setText(_translate("Dialog", "A", None))
        self.label_11.setText(_translate("Dialog", "Vanne 3 voies", None))
        self.progressBar.setFormat(_translate("Dialog", "%p %", None))
        self.label_30.setText(_translate("Dialog", "Conso heures creuses ", None))
        self.label_31.setText(_translate("Dialog", "kWh", None))
        self.label_32.setText(_translate("Dialog", "Conso heures pleines", None))
        self.label_33.setText(_translate("Dialog", "kWh", None))
        self.label_37.setText(_translate("Dialog", "Circulateur", None))
        self.label_27.setText(_translate("Dialog", "A", None))
        self.label_51.setText(_translate("Dialog", "Chauf. Elec.", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab1), _translate("Dialog", "Chauffage", None))
        self.groupBox_3.setTitle(_translate("Dialog", "Données compteur", None))
        self.label_9.setText(_translate("Dialog", "Wh", None))
        self.label_13.setText(_translate("Dialog", "Wh", None))
        self.label_14.setText(_translate("Dialog", "Compteur h. creuses", None))
        self.label_15.setText(_translate("Dialog", "Compteur h. pleines", None))
        self.label_16.setText(_translate("Dialog", "Courant", None))
        self.label_17.setText(_translate("Dialog", "Puissance. Apparente", None))
        self.label_18.setText(_translate("Dialog", "A", None))
        self.label_19.setText(_translate("Dialog", "VA", None))
        self.label_34.setText(_translate("Dialog", "Tarif en cours", None))
        self.label_35.setText(_translate("Dialog", "...", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab2), _translate("Dialog", "EDF", None))
        self.groupBox_4.setTitle(_translate("Dialog", "Vanne 3 voies régulation temperature", None))
        self.label_25.setText(_translate("Dialog", "°C", None))
        self.label_26.setText(_translate("Dialog", " T. sortie vanne ", None))
        self.progressBar_3.setFormat(_translate("Dialog", "%v %", None))
        self.label_24.setText(_translate("Dialog", "Ouverture vanne", None))
        self.label_21.setText(_translate("Dialog", "T. consigne eau", None))
        self.label_20.setText(_translate("Dialog", "°C", None))
        self.groupBox_5.setTitle(_translate("Dialog", "Chauffage electrique thermoplongeur", None))
        self.label_22.setText(_translate("Dialog", "°C", None))
        self.label_23.setText(_translate("Dialog", " T. cuve milieu", None))
        self.label_12.setText(_translate("Dialog", "Puissance", None))
        self.progressBar_2.setFormat(_translate("Dialog", "%v W", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab3), _translate("Dialog", "Regulation", None))
        self.groupBox_9.setTitle(_translate("Dialog", "Resultats", None))
        self.label_56.setText(_translate("Dialog", "Energie / J", None))
        self.label_58.setText(_translate("Dialog", "kWh", None))
        self.label_52.setText(_translate("Dialog", "kW", None))
        self.label_50.setText(_translate("Dialog", "Puissance", None))
        self.groupBox_6.setTitle(_translate("Dialog", "Temp. ballon", None))
        self.label_38.setText(_translate("Dialog", "Millieu", None))
        self.label_39.setText(_translate("Dialog", "Bas", None))
        self.label_41.setText(_translate("Dialog", "°C", None))
        self.label_42.setText(_translate("Dialog", "°C", None))
        self.label_43.setText(_translate("Dialog", "°C", None))
        self.label_44.setText(_translate("Dialog", "Haut", None))
        self.groupBox_8.setTitle(_translate("Dialog", "Fonctionnement", None))
        self.label_54.setText(_translate("Dialog", "L/h", None))
        self.label_55.setText(_translate("Dialog", "Débit", None))
        self.label_36.setText(_translate("Dialog", "A", None))
        self.label_57.setText(_translate("Dialog", "Circulateur", None))
        self.groupBox_7.setTitle(_translate("Dialog", "Temp. circuit solaire", None))
        self.label_40.setText(_translate("Dialog", "Départ", None))
        self.label_45.setText(_translate("Dialog", "Retour", None))
        self.label_46.setText(_translate("Dialog", "°C", None))
        self.label_47.setText(_translate("Dialog", "°C", None))
        self.label_48.setText(_translate("Dialog", "°C", None))
        self.label_49.setText(_translate("Dialog", "Capteurs", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab4), _translate("Dialog", "Solaire", None))
        self.label_28.setText(_translate("Dialog", "Etat : ", None))
        self.label_29.setText(_translate("Dialog", "<html><head/><body><p><span style=\" color:#0000ff;\">Attente ...</span></p></body></html>", None))
        self.pushButton_quit.setText(_translate("Dialog", "Quitter", None))
        self.label_60.setText(_translate("Dialog", "Lecture Chauffage", None))
        self.label_61.setText(_translate("Dialog", "Lecture Solaire", None))

