# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'HDMI_Chauffage.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(441, 417)
        Dialog.setAutoFillBackground(False)
        self.tabWidget = QtWidgets.QTabWidget(Dialog)
        self.tabWidget.setGeometry(QtCore.QRect(10, 10, 421, 361))
        self.tabWidget.setFocusPolicy(QtCore.Qt.NoFocus)
        self.tabWidget.setObjectName("tabWidget")
        self.tab1 = QtWidgets.QWidget()
        self.tab1.setObjectName("tab1")
        self.groupBox = QtWidgets.QGroupBox(self.tab1)
        self.groupBox.setEnabled(True)
        self.groupBox.setGeometry(QtCore.QRect(10, 10, 391, 141))
        font = QtGui.QFont()
        font.setKerning(True)
        self.groupBox.setFont(font)
        self.groupBox.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.groupBox.setAutoFillBackground(False)
        #self.groupBox.setStyleSheet("")
        self.groupBox.setFlat(False)
        self.groupBox.setObjectName("groupBox")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setGeometry(QtCore.QRect(30, 30, 71, 20))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setGeometry(QtCore.QRect(150, 30, 91, 20))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setGeometry(QtCore.QRect(150, 70, 91, 20))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_3.setFont(font)
        self.label_3.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.label_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName("label_3")
        self.lcdNumber_3 = QtWidgets.QLCDNumber(self.groupBox)
        self.lcdNumber_3.setGeometry(QtCore.QRect(250, 60, 81, 31))
        self.lcdNumber_3.setStyleSheet("color: rgb(0, 0, 255);\n"
"background-color: rgb(237, 255, 240)")
        self.lcdNumber_3.setSmallDecimalPoint(True)
        self.lcdNumber_3.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.lcdNumber_3.setObjectName("lcdNumber_3")
        self.lcdNumber_2 = QtWidgets.QLCDNumber(self.groupBox)
        self.lcdNumber_2.setGeometry(QtCore.QRect(250, 20, 81, 31))
        self.lcdNumber_2.setStyleSheet("color: rgb(0, 0, 255);\n"
"background-color: rgb(237, 255, 240)")
        self.lcdNumber_2.setSmallDecimalPoint(True)
        self.lcdNumber_2.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.lcdNumber_2.setProperty("value", 0.0)
        self.lcdNumber_2.setObjectName("lcdNumber_2")
        self.lcdNumber_4 = QtWidgets.QLCDNumber(self.groupBox)
        self.lcdNumber_4.setGeometry(QtCore.QRect(250, 100, 81, 31))
        self.lcdNumber_4.setStyleSheet("color: rgb(0, 0, 255);\n"
"background-color: rgb(237, 255, 240)\n"
"")
        self.lcdNumber_4.setLineWidth(1)
        self.lcdNumber_4.setSmallDecimalPoint(True)
        self.lcdNumber_4.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.lcdNumber_4.setObjectName("lcdNumber_4")
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        self.label_4.setGeometry(QtCore.QRect(140, 110, 101, 20))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_4.setFont(font)
        self.label_4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.groupBox)
        self.label_5.setGeometry(QtCore.QRect(340, 30, 21, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.groupBox)
        self.label_6.setGeometry(QtCore.QRect(340, 70, 21, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.groupBox)
        self.label_7.setGeometry(QtCore.QRect(340, 110, 21, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.groupBox)
        self.label_8.setGeometry(QtCore.QRect(110, 70, 21, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.lineEdit = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit.setGeometry(QtCore.QRect(30, 60, 71, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.lineEdit.setFont(font)
        self.lineEdit.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.lineEdit.setStyleSheet("color: rgb(255, 0, 0);\n"
"background-color: rgb(237, 255, 240)")
        self.lineEdit.setInputMethodHints(QtCore.Qt.ImhDigitsOnly)
        self.lineEdit.setInputMask("")
        self.lineEdit.setText("")
        self.lineEdit.setMaxLength(5)
        self.lineEdit.setFrame(True)
        self.lineEdit.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit.setClearButtonEnabled(False)
        self.lineEdit.setObjectName("lineEdit")
        self.groupBox_2 = QtWidgets.QGroupBox(self.tab1)
        self.groupBox_2.setGeometry(QtCore.QRect(10, 150, 391, 171))
        self.groupBox_2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.groupBox_2.setFlat(False)
        self.groupBox_2.setObjectName("groupBox_2")
        self.pushButton = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton.setGeometry(QtCore.QRect(10, 30, 91, 31))
        self.pushButton.setFocusPolicy(QtCore.Qt.NoFocus)
        self.pushButton.setStyleSheet("")
        self.pushButton.setText("")
        self.pushButton.setCheckable(False)
        self.pushButton.setObjectName("pushButton")
        self.label_10 = QtWidgets.QLabel(self.groupBox_2)
        self.label_10.setGeometry(QtCore.QRect(210, 30, 31, 31))
        font = QtGui.QFont()
        font.setFamily("Sans Serif")
        font.setPointSize(11)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_10.setFont(font)
        self.label_10.setStyleSheet("background-color: rgb(255, 0, 0);")
        self.label_10.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.label_10.setFrameShadow(QtWidgets.QFrame.Raised)
        self.label_10.setText("")
        self.label_10.setTextFormat(QtCore.Qt.AutoText)
        self.label_10.setScaledContents(True)
        self.label_10.setAlignment(QtCore.Qt.AlignCenter)
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(self.groupBox_2)
        self.label_11.setGeometry(QtCore.QRect(0, 70, 101, 20))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_11.setFont(font)
        self.label_11.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_11.setObjectName("label_11")
        self.progressBar = QtWidgets.QProgressBar(self.groupBox_2)
        self.progressBar.setGeometry(QtCore.QRect(110, 70, 271, 16))
        self.progressBar.setProperty("value", 0)
        self.progressBar.setTextVisible(True)
        self.progressBar.setObjectName("progressBar")
        self.label_30 = QtWidgets.QLabel(self.groupBox_2)
        self.label_30.setGeometry(QtCore.QRect(60, 100, 151, 21))
        font = QtGui.QFont()
        font.setFamily("Century Schoolbook L")
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        self.label_30.setFont(font)
        self.label_30.setStyleSheet("")
        self.label_30.setObjectName("label_30")
        self.label_31 = QtWidgets.QLabel(self.groupBox_2)
        self.label_31.setGeometry(QtCore.QRect(330, 90, 41, 21))
        self.label_31.setStyleSheet("font: 12pt \"Sans Serif\";")
        self.label_31.setObjectName("label_31")
        self.lcdNumber_12 = QtWidgets.QLCDNumber(self.groupBox_2)
        self.lcdNumber_12.setGeometry(QtCore.QRect(210, 90, 111, 31))
        self.lcdNumber_12.setStyleSheet("background-color: rgb(220, 251, 255);\n"
"color: rgb(0, 0, 127);")
        self.lcdNumber_12.setSmallDecimalPoint(True)
        self.lcdNumber_12.setDigitCount(7)
        self.lcdNumber_12.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.lcdNumber_12.setProperty("intValue", 0)
        self.lcdNumber_12.setObjectName("lcdNumber_12")
        self.lcdNumber_13 = QtWidgets.QLCDNumber(self.groupBox_2)
        self.lcdNumber_13.setGeometry(QtCore.QRect(210, 130, 111, 31))
        self.lcdNumber_13.setStyleSheet("background-color: rgb(220, 251, 255);\n"
"color: rgb(0, 0, 127);")
        self.lcdNumber_13.setSmallDecimalPoint(True)
        self.lcdNumber_13.setDigitCount(7)
        self.lcdNumber_13.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.lcdNumber_13.setProperty("intValue", 0)
        self.lcdNumber_13.setObjectName("lcdNumber_13")
        self.label_32 = QtWidgets.QLabel(self.groupBox_2)
        self.label_32.setGeometry(QtCore.QRect(60, 140, 151, 21))
        font = QtGui.QFont()
        font.setFamily("Century Schoolbook L")
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        self.label_32.setFont(font)
        self.label_32.setStyleSheet("")
        self.label_32.setObjectName("label_32")
        self.label_33 = QtWidgets.QLabel(self.groupBox_2)
        self.label_33.setGeometry(QtCore.QRect(330, 130, 41, 21))
        self.label_33.setStyleSheet("font: 12pt \"Sans Serif\";")
        self.label_33.setObjectName("label_33")
        self.label_37 = QtWidgets.QLabel(self.groupBox_2)
        self.label_37.setGeometry(QtCore.QRect(110, 40, 91, 20))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_37.setFont(font)
        self.label_37.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_37.setObjectName("label_37")
        self.label_27 = QtWidgets.QLabel(self.groupBox_2)
        self.label_27.setGeometry(QtCore.QRect(350, 30, 31, 31))
        font = QtGui.QFont()
        font.setFamily("Sans Serif")
        font.setPointSize(11)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_27.setFont(font)
        self.label_27.setStyleSheet("background-color: rgb(255, 0, 0);")
        self.label_27.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.label_27.setFrameShadow(QtWidgets.QFrame.Raised)
        self.label_27.setText("")
        self.label_27.setTextFormat(QtCore.Qt.AutoText)
        self.label_27.setScaledContents(True)
        self.label_27.setAlignment(QtCore.Qt.AlignCenter)
        self.label_27.setObjectName("label_27")
        self.label_51 = QtWidgets.QLabel(self.groupBox_2)
        self.label_51.setGeometry(QtCore.QRect(250, 40, 91, 20))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_51.setFont(font)
        self.label_51.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_51.setObjectName("label_51")
        self.groupBox_2.raise_()
        self.groupBox.raise_()
        self.tabWidget.addTab(self.tab1, "")
        self.tab2 = QtWidgets.QWidget()
        self.tab2.setObjectName("tab2")
        self.groupBox_3 = QtWidgets.QGroupBox(self.tab2)
        self.groupBox_3.setGeometry(QtCore.QRect(10, 10, 391, 171))
        self.groupBox_3.setObjectName("groupBox_3")
        self.lcdNumber = QtWidgets.QLCDNumber(self.groupBox_3)
        self.lcdNumber.setGeometry(QtCore.QRect(190, 20, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.lcdNumber.setFont(font)
        self.lcdNumber.setStyleSheet("background-color: rgb(220, 251, 255);\n"
"color: rgb(250, 0, 255);")
        self.lcdNumber.setSmallDecimalPoint(False)
        self.lcdNumber.setDigitCount(8)
        self.lcdNumber.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.lcdNumber.setProperty("intValue", 0)
        self.lcdNumber.setObjectName("lcdNumber")
        self.lcdNumber_5 = QtWidgets.QLCDNumber(self.groupBox_3)
        self.lcdNumber_5.setGeometry(QtCore.QRect(190, 50, 111, 31))
        self.lcdNumber_5.setStyleSheet("background-color: rgb(220, 251, 255);\n"
"font: 9pt \"Sans Serif\";\n"
"color: rgb(250, 0, 255);")
        self.lcdNumber_5.setSmallDecimalPoint(False)
        self.lcdNumber_5.setDigitCount(8)
        self.lcdNumber_5.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.lcdNumber_5.setProperty("intValue", 0)
        self.lcdNumber_5.setObjectName("lcdNumber_5")
        self.label_9 = QtWidgets.QLabel(self.groupBox_3)
        self.label_9.setGeometry(QtCore.QRect(310, 30, 31, 21))
        self.label_9.setStyleSheet("font: 12pt \"Sans Serif\";")
        self.label_9.setObjectName("label_9")
        self.label_13 = QtWidgets.QLabel(self.groupBox_3)
        self.label_13.setGeometry(QtCore.QRect(310, 60, 31, 21))
        self.label_13.setStyleSheet("font: 12pt \"Sans Serif\";")
        self.label_13.setObjectName("label_13")
        self.label_14 = QtWidgets.QLabel(self.groupBox_3)
        self.label_14.setGeometry(QtCore.QRect(40, 30, 141, 21))
        self.label_14.setStyleSheet("font: 10pt \"Sans Serif\";")
        self.label_14.setObjectName("label_14")
        self.label_15 = QtWidgets.QLabel(self.groupBox_3)
        self.label_15.setGeometry(QtCore.QRect(40, 60, 141, 21))
        self.label_15.setStyleSheet("font: 10pt \"Sans Serif\";")
        self.label_15.setObjectName("label_15")
        self.label_16 = QtWidgets.QLabel(self.groupBox_3)
        self.label_16.setGeometry(QtCore.QRect(40, 120, 61, 21))
        self.label_16.setStyleSheet("font: 10pt \"Sans Serif\";")
        self.label_16.setObjectName("label_16")
        self.label_17 = QtWidgets.QLabel(self.groupBox_3)
        self.label_17.setGeometry(QtCore.QRect(40, 90, 151, 21))
        self.label_17.setStyleSheet("font: 10pt \"Sans Serif\";")
        self.label_17.setObjectName("label_17")
        self.lcdNumber_6 = QtWidgets.QLCDNumber(self.groupBox_3)
        self.lcdNumber_6.setGeometry(QtCore.QRect(190, 110, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.lcdNumber_6.setFont(font)
        self.lcdNumber_6.setStyleSheet("background-color: rgb(220, 251, 255);\n"
"color: rgb(250, 0, 255);")
        self.lcdNumber_6.setSmallDecimalPoint(False)
        self.lcdNumber_6.setDigitCount(8)
        self.lcdNumber_6.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.lcdNumber_6.setProperty("value", 0.0)
        self.lcdNumber_6.setProperty("intValue", 0)
        self.lcdNumber_6.setObjectName("lcdNumber_6")
        self.label_18 = QtWidgets.QLabel(self.groupBox_3)
        self.label_18.setGeometry(QtCore.QRect(310, 120, 31, 21))
        self.label_18.setStyleSheet("font: 12pt \"Sans Serif\";")
        self.label_18.setObjectName("label_18")
        self.lcdNumber_7 = QtWidgets.QLCDNumber(self.groupBox_3)
        self.lcdNumber_7.setGeometry(QtCore.QRect(190, 80, 111, 31))
        font = QtGui.QFont()
        font.setFamily("Sans Serif")
        font.setPointSize(9)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        self.lcdNumber_7.setFont(font)
        self.lcdNumber_7.setStyleSheet("background-color: rgb(220, 251, 255);\n"
"font: 9pt \"Sans Serif\";\n"
"color: rgb(250, 0, 255);")
        self.lcdNumber_7.setSmallDecimalPoint(False)
        self.lcdNumber_7.setDigitCount(8)
        self.lcdNumber_7.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.lcdNumber_7.setProperty("intValue", 0)
        self.lcdNumber_7.setObjectName("lcdNumber_7")
        self.label_19 = QtWidgets.QLabel(self.groupBox_3)
        self.label_19.setGeometry(QtCore.QRect(310, 90, 31, 21))
        self.label_19.setStyleSheet("font: 12pt \"Sans Serif\";")
        self.label_19.setObjectName("label_19")
        self.label_34 = QtWidgets.QLabel(self.groupBox_3)
        self.label_34.setGeometry(QtCore.QRect(40, 150, 101, 21))
        self.label_34.setStyleSheet("font: 10pt \"Sans Serif\";")
        self.label_34.setObjectName("label_34")
        self.label_35 = QtWidgets.QLabel(self.groupBox_3)
        self.label_35.setGeometry(QtCore.QRect(220, 150, 81, 21))
        font = QtGui.QFont()
        font.setFamily("Sans Serif")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_35.setFont(font)
        self.label_35.setStyleSheet("font: 14pt \"Sans Serif\";\n"
"background-color: rgb(170, 170, 255);")
        self.label_35.setFrameShape(QtWidgets.QFrame.Box)
        self.label_35.setAlignment(QtCore.Qt.AlignCenter)
        self.label_35.setObjectName("label_35")
        self.tabWidget.addTab(self.tab2, "")
        self.tab3 = QtWidgets.QWidget()
        self.tab3.setObjectName("tab3")
        self.groupBox_4 = QtWidgets.QGroupBox(self.tab3)
        self.groupBox_4.setGeometry(QtCore.QRect(10, 10, 391, 141))
        self.groupBox_4.setObjectName("groupBox_4")
        self.label_25 = QtWidgets.QLabel(self.groupBox_4)
        self.label_25.setGeometry(QtCore.QRect(340, 80, 21, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_25.setFont(font)
        self.label_25.setObjectName("label_25")
        self.label_26 = QtWidgets.QLabel(self.groupBox_4)
        self.label_26.setGeometry(QtCore.QRect(130, 80, 111, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_26.setFont(font)
        self.label_26.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_26.setObjectName("label_26")
        self.lcdNumber_11 = QtWidgets.QLCDNumber(self.groupBox_4)
        self.lcdNumber_11.setGeometry(QtCore.QRect(250, 70, 81, 31))
        self.lcdNumber_11.setStyleSheet("color: rgb(0, 0, 255);\n"
"background-color: rgb(237, 255, 240)")
        self.lcdNumber_11.setSmallDecimalPoint(True)
        self.lcdNumber_11.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.lcdNumber_11.setProperty("value", 0.0)
        self.lcdNumber_11.setObjectName("lcdNumber_11")
        self.progressBar_3 = QtWidgets.QProgressBar(self.groupBox_4)
        self.progressBar_3.setGeometry(QtCore.QRect(130, 110, 261, 16))
        self.progressBar_3.setMaximum(100)
        self.progressBar_3.setProperty("value", 0)
        self.progressBar_3.setTextVisible(True)
        self.progressBar_3.setObjectName("progressBar_3")
        self.label_24 = QtWidgets.QLabel(self.groupBox_4)
        self.label_24.setGeometry(QtCore.QRect(0, 110, 121, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_24.setFont(font)
        self.label_24.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_24.setObjectName("label_24")
        self.label_21 = QtWidgets.QLabel(self.groupBox_4)
        self.label_21.setGeometry(QtCore.QRect(130, 40, 111, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_21.setFont(font)
        self.label_21.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_21.setObjectName("label_21")
        self.lcdNumber_8 = QtWidgets.QLCDNumber(self.groupBox_4)
        self.lcdNumber_8.setGeometry(QtCore.QRect(250, 30, 81, 31))
        self.lcdNumber_8.setStyleSheet("color: rgb(0, 0, 255);\n"
"background-color: rgb(237, 255, 240)")
        self.lcdNumber_8.setSmallDecimalPoint(True)
        self.lcdNumber_8.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.lcdNumber_8.setProperty("value", 0.0)
        self.lcdNumber_8.setObjectName("lcdNumber_8")
        self.label_20 = QtWidgets.QLabel(self.groupBox_4)
        self.label_20.setGeometry(QtCore.QRect(340, 40, 21, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_20.setFont(font)
        self.label_20.setObjectName("label_20")
        self.groupBox_5 = QtWidgets.QGroupBox(self.tab3)
        self.groupBox_5.setGeometry(QtCore.QRect(10, 160, 391, 101))
        self.groupBox_5.setObjectName("groupBox_5")
        self.label_22 = QtWidgets.QLabel(self.groupBox_5)
        self.label_22.setGeometry(QtCore.QRect(340, 40, 21, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_22.setFont(font)
        self.label_22.setObjectName("label_22")
        self.label_23 = QtWidgets.QLabel(self.groupBox_5)
        self.label_23.setGeometry(QtCore.QRect(110, 40, 131, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_23.setFont(font)
        self.label_23.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_23.setObjectName("label_23")
        self.lcdNumber_9 = QtWidgets.QLCDNumber(self.groupBox_5)
        self.lcdNumber_9.setGeometry(QtCore.QRect(250, 30, 81, 31))
        self.lcdNumber_9.setStyleSheet("color: rgb(0, 0, 255);\n"
"background-color: rgb(237, 255, 240)")
        self.lcdNumber_9.setSmallDecimalPoint(True)
        self.lcdNumber_9.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.lcdNumber_9.setProperty("value", 0.0)
        self.lcdNumber_9.setObjectName("lcdNumber_9")
        self.label_12 = QtWidgets.QLabel(self.groupBox_5)
        self.label_12.setGeometry(QtCore.QRect(140, 80, 101, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_12.setFont(font)
        self.label_12.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_12.setObjectName("label_12")
        self.progressBar_2 = QtWidgets.QProgressBar(self.groupBox_5)
        self.progressBar_2.setGeometry(QtCore.QRect(250, 80, 131, 23))
        self.progressBar_2.setMaximum(6000)
        self.progressBar_2.setProperty("value", 0)
        self.progressBar_2.setTextVisible(True)
        self.progressBar_2.setObjectName("progressBar_2")
        self.tabWidget.addTab(self.tab3, "")
        self.tab4 = QtWidgets.QWidget()
        self.tab4.setObjectName("tab4")
        self.groupBox_9 = QtWidgets.QGroupBox(self.tab4)
        self.groupBox_9.setGeometry(QtCore.QRect(200, 160, 211, 111))
        self.groupBox_9.setObjectName("groupBox_9")
        self.label_56 = QtWidgets.QLabel(self.groupBox_9)
        self.label_56.setGeometry(QtCore.QRect(0, 70, 71, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_56.setFont(font)
        self.label_56.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.label_56.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_56.setObjectName("label_56")
        self.lcdNumber_23 = QtWidgets.QLCDNumber(self.groupBox_9)
        self.lcdNumber_23.setGeometry(QtCore.QRect(80, 60, 81, 31))
        self.lcdNumber_23.setStyleSheet("color: rgb(0, 0, 255);\n"
"background-color: rgb(237, 255, 240)")
        self.lcdNumber_23.setSmallDecimalPoint(True)
        self.lcdNumber_23.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.lcdNumber_23.setObjectName("lcdNumber_23")
        self.label_58 = QtWidgets.QLabel(self.groupBox_9)
        self.label_58.setGeometry(QtCore.QRect(170, 70, 41, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_58.setFont(font)
        self.label_58.setObjectName("label_58")
        self.label_52 = QtWidgets.QLabel(self.groupBox_9)
        self.label_52.setGeometry(QtCore.QRect(170, 30, 31, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_52.setFont(font)
        self.label_52.setObjectName("label_52")
        self.lcdNumber_20 = QtWidgets.QLCDNumber(self.groupBox_9)
        self.lcdNumber_20.setGeometry(QtCore.QRect(80, 20, 81, 31))
        self.lcdNumber_20.setStyleSheet("color: rgb(0, 0, 255);\n"
"background-color: rgb(237, 255, 240)")
        self.lcdNumber_20.setSmallDecimalPoint(True)
        self.lcdNumber_20.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.lcdNumber_20.setObjectName("lcdNumber_20")
        self.label_50 = QtWidgets.QLabel(self.groupBox_9)
        self.label_50.setGeometry(QtCore.QRect(0, 30, 71, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_50.setFont(font)
        self.label_50.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.label_50.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_50.setObjectName("label_50")
        self.groupBox_6 = QtWidgets.QGroupBox(self.tab4)
        self.groupBox_6.setGeometry(QtCore.QRect(10, 10, 181, 141))
        self.groupBox_6.setObjectName("groupBox_6")
        self.label_38 = QtWidgets.QLabel(self.groupBox_6)
        self.label_38.setGeometry(QtCore.QRect(0, 70, 51, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_38.setFont(font)
        self.label_38.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.label_38.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_38.setObjectName("label_38")
        self.lcdNumber_14 = QtWidgets.QLCDNumber(self.groupBox_6)
        self.lcdNumber_14.setGeometry(QtCore.QRect(60, 60, 81, 31))
        self.lcdNumber_14.setStyleSheet("color: rgb(0, 0, 255);\n"
"background-color: rgb(237, 255, 240)")
        self.lcdNumber_14.setSmallDecimalPoint(True)
        self.lcdNumber_14.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.lcdNumber_14.setObjectName("lcdNumber_14")
        self.lcdNumber_16 = QtWidgets.QLCDNumber(self.groupBox_6)
        self.lcdNumber_16.setGeometry(QtCore.QRect(60, 100, 81, 31))
        self.lcdNumber_16.setStyleSheet("color: rgb(0, 0, 255);\n"
"background-color: rgb(237, 255, 240)\n"
"")
        self.lcdNumber_16.setLineWidth(1)
        self.lcdNumber_16.setSmallDecimalPoint(True)
        self.lcdNumber_16.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.lcdNumber_16.setObjectName("lcdNumber_16")
        self.label_39 = QtWidgets.QLabel(self.groupBox_6)
        self.label_39.setGeometry(QtCore.QRect(10, 110, 41, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_39.setFont(font)
        self.label_39.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_39.setObjectName("label_39")
        self.label_41 = QtWidgets.QLabel(self.groupBox_6)
        self.label_41.setGeometry(QtCore.QRect(150, 70, 21, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_41.setFont(font)
        self.label_41.setObjectName("label_41")
        self.label_42 = QtWidgets.QLabel(self.groupBox_6)
        self.label_42.setGeometry(QtCore.QRect(150, 110, 21, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_42.setFont(font)
        self.label_42.setObjectName("label_42")
        self.label_43 = QtWidgets.QLabel(self.groupBox_6)
        self.label_43.setGeometry(QtCore.QRect(150, 30, 21, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_43.setFont(font)
        self.label_43.setObjectName("label_43")
        self.lcdNumber_17 = QtWidgets.QLCDNumber(self.groupBox_6)
        self.lcdNumber_17.setGeometry(QtCore.QRect(60, 20, 81, 31))
        self.lcdNumber_17.setStyleSheet("color: rgb(0, 0, 255);\n"
"background-color: rgb(237, 255, 240)")
        self.lcdNumber_17.setLineWidth(1)
        self.lcdNumber_17.setSmallDecimalPoint(True)
        self.lcdNumber_17.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.lcdNumber_17.setProperty("value", 0.0)
        self.lcdNumber_17.setProperty("intValue", 0)
        self.lcdNumber_17.setObjectName("lcdNumber_17")
        self.label_44 = QtWidgets.QLabel(self.groupBox_6)
        self.label_44.setGeometry(QtCore.QRect(10, 30, 41, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_44.setFont(font)
        self.label_44.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_44.setObjectName("label_44")
        self.groupBox_8 = QtWidgets.QGroupBox(self.tab4)
        self.groupBox_8.setGeometry(QtCore.QRect(10, 160, 181, 111))
        self.groupBox_8.setObjectName("groupBox_8")
        self.label_54 = QtWidgets.QLabel(self.groupBox_8)
        self.label_54.setGeometry(QtCore.QRect(150, 30, 31, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_54.setFont(font)
        self.label_54.setObjectName("label_54")
        self.lcdNumber_22 = QtWidgets.QLCDNumber(self.groupBox_8)
        self.lcdNumber_22.setGeometry(QtCore.QRect(60, 20, 81, 31))
        self.lcdNumber_22.setStyleSheet("color: rgb(0, 0, 255);\n"
"background-color: rgb(237, 255, 240)")
        self.lcdNumber_22.setSmallDecimalPoint(True)
        self.lcdNumber_22.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.lcdNumber_22.setProperty("value", 0.0)
        self.lcdNumber_22.setObjectName("lcdNumber_22")
        self.label_55 = QtWidgets.QLabel(self.groupBox_8)
        self.label_55.setGeometry(QtCore.QRect(10, 30, 41, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_55.setFont(font)
        self.label_55.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_55.setObjectName("label_55")
        self.label_57 = QtWidgets.QLabel(self.groupBox_8)
        self.label_57.setGeometry(QtCore.QRect(10, 70, 81, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_57.setFont(font)
        self.label_57.setAlignment(QtCore.Qt.AlignCenter)
        self.label_57.setObjectName("label_57")
        self.label_36 = QtWidgets.QLabel(self.groupBox_8)
        self.label_36.setGeometry(QtCore.QRect(110, 60, 31, 31))
        font = QtGui.QFont()
        font.setFamily("Sans Serif")
        font.setPointSize(11)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_36.setFont(font)
        self.label_36.setStyleSheet("background-color: rgb(255, 0, 0);")
        self.label_36.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.label_36.setFrameShadow(QtWidgets.QFrame.Raised)
        self.label_36.setText("")
        self.label_36.setTextFormat(QtCore.Qt.AutoText)
        self.label_36.setScaledContents(True)
        self.label_36.setAlignment(QtCore.Qt.AlignCenter)
        self.label_36.setObjectName("label_36")
        self.groupBox_7 = QtWidgets.QGroupBox(self.tab4)
        self.groupBox_7.setGeometry(QtCore.QRect(200, 10, 211, 141))
        self.groupBox_7.setObjectName("groupBox_7")
        self.label_40 = QtWidgets.QLabel(self.groupBox_7)
        self.label_40.setGeometry(QtCore.QRect(20, 70, 51, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_40.setFont(font)
        self.label_40.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.label_40.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_40.setObjectName("label_40")
        self.lcdNumber_15 = QtWidgets.QLCDNumber(self.groupBox_7)
        self.lcdNumber_15.setGeometry(QtCore.QRect(80, 60, 81, 31))
        self.lcdNumber_15.setStyleSheet("color: rgb(0, 0, 255);\n"
"background-color: rgb(237, 255, 240)")
        self.lcdNumber_15.setSmallDecimalPoint(True)
        self.lcdNumber_15.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.lcdNumber_15.setObjectName("lcdNumber_15")
        self.lcdNumber_18 = QtWidgets.QLCDNumber(self.groupBox_7)
        self.lcdNumber_18.setGeometry(QtCore.QRect(80, 100, 81, 31))
        self.lcdNumber_18.setStyleSheet("color: rgb(0, 0, 255);\n"
"background-color: rgb(237, 255, 240)\n"
"")
        self.lcdNumber_18.setLineWidth(1)
        self.lcdNumber_18.setSmallDecimalPoint(True)
        self.lcdNumber_18.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.lcdNumber_18.setObjectName("lcdNumber_18")
        self.label_45 = QtWidgets.QLabel(self.groupBox_7)
        self.label_45.setGeometry(QtCore.QRect(20, 110, 51, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_45.setFont(font)
        self.label_45.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_45.setObjectName("label_45")
        self.label_46 = QtWidgets.QLabel(self.groupBox_7)
        self.label_46.setGeometry(QtCore.QRect(170, 70, 21, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_46.setFont(font)
        self.label_46.setObjectName("label_46")
        self.label_47 = QtWidgets.QLabel(self.groupBox_7)
        self.label_47.setGeometry(QtCore.QRect(170, 110, 21, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_47.setFont(font)
        self.label_47.setObjectName("label_47")
        self.label_48 = QtWidgets.QLabel(self.groupBox_7)
        self.label_48.setGeometry(QtCore.QRect(170, 30, 21, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_48.setFont(font)
        self.label_48.setObjectName("label_48")
        self.lcdNumber_19 = QtWidgets.QLCDNumber(self.groupBox_7)
        self.lcdNumber_19.setGeometry(QtCore.QRect(80, 20, 81, 31))
        self.lcdNumber_19.setStyleSheet("color: rgb(0, 0, 255);\n"
"background-color: rgb(237, 255, 240)")
        self.lcdNumber_19.setSmallDecimalPoint(True)
        self.lcdNumber_19.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.lcdNumber_19.setProperty("value", 0.0)
        self.lcdNumber_19.setObjectName("lcdNumber_19")
        self.label_49 = QtWidgets.QLabel(self.groupBox_7)
        self.label_49.setGeometry(QtCore.QRect(10, 30, 61, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_49.setFont(font)
        self.label_49.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_49.setObjectName("label_49")
        self.tabWidget.addTab(self.tab4, "")
        self.label_28 = QtWidgets.QLabel(Dialog)
        self.label_28.setGeometry(QtCore.QRect(10, 380, 61, 21))
        self.label_28.setAccessibleName("")
        self.label_28.setObjectName("label_28")
        self.label_29 = QtWidgets.QLabel(Dialog)
        self.label_29.setGeometry(QtCore.QRect(60, 380, 271, 21))
        font = QtGui.QFont()
        font.setItalic(True)
        self.label_29.setFont(font)
        self.label_29.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_29.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label_29.setTextFormat(QtCore.Qt.AutoText)
        self.label_29.setObjectName("label_29")
        self.pushButton_quit = QtWidgets.QPushButton(Dialog)
        self.pushButton_quit.setGeometry(QtCore.QRect(350, 380, 79, 25))
        self.pushButton_quit.setFocusPolicy(QtCore.Qt.NoFocus)
        self.pushButton_quit.setObjectName("pushButton_quit")
        self.label_53 = QtWidgets.QLabel(Dialog)
        self.label_53.setGeometry(QtCore.QRect(140, 400, 15, 15))
        self.label_53.setStyleSheet("background-color: rgb(233, 225, 255);")
        self.label_53.setFrameShape(QtWidgets.QFrame.Panel)
        self.label_53.setText("")
        self.label_53.setObjectName("label_53")
        self.label_59 = QtWidgets.QLabel(Dialog)
        self.label_59.setGeometry(QtCore.QRect(300, 400, 15, 15))
        self.label_59.setStyleSheet("background-color: rgb(233, 225, 255);")
        self.label_59.setFrameShape(QtWidgets.QFrame.Panel)
        self.label_59.setText("")
        self.label_59.setObjectName("label_59")
        self.label_60 = QtWidgets.QLabel(Dialog)
        self.label_60.setGeometry(QtCore.QRect(10, 400, 131, 16))
        font = QtGui.QFont()
        font.setFamily("Century Schoolbook L")
        font.setPointSize(11)
        font.setItalic(True)
        self.label_60.setFont(font)
        self.label_60.setObjectName("label_60")
        self.label_61 = QtWidgets.QLabel(Dialog)
        self.label_61.setGeometry(QtCore.QRect(190, 400, 111, 16))
        font = QtGui.QFont()
        font.setFamily("Century Schoolbook L")
        font.setPointSize(11)
        font.setItalic(True)
        self.label_61.setFont(font)
        self.label_61.setObjectName("label_61")

        self.retranslateUi(Dialog)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Dialog)
        Dialog.setTabOrder(self.tabWidget, self.pushButton_quit)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Solaire et chauffage"))
        self.groupBox.setTitle(_translate("Dialog", "Températures"))
        self.label.setText(_translate("Dialog", "Consigne "))
        self.label_2.setText(_translate("Dialog", " Exterieure "))
        self.label_3.setText(_translate("Dialog", "Interieur "))
        self.label_4.setText(_translate("Dialog", "Ballon solaire"))
        self.label_5.setText(_translate("Dialog", "°C"))
        self.label_6.setText(_translate("Dialog", "°C"))
        self.label_7.setText(_translate("Dialog", "°C"))
        self.label_8.setText(_translate("Dialog", "°C"))
        self.groupBox_2.setTitle(_translate("Dialog", "Commande, etat"))
        self.label_11.setText(_translate("Dialog", "Vanne 3 voies"))
        self.progressBar.setFormat(_translate("Dialog", "%p %"))
        self.label_30.setText(_translate("Dialog", "Conso heures creuses "))
        self.label_31.setText(_translate("Dialog", "kWh"))
        self.label_32.setText(_translate("Dialog", "Conso heures pleines"))
        self.label_33.setText(_translate("Dialog", "kWh"))
        self.label_37.setText(_translate("Dialog", "Circulateur"))
        self.label_51.setText(_translate("Dialog", "Chauf. Elec."))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab1), _translate("Dialog", "Chauffage"))
        self.groupBox_3.setTitle(_translate("Dialog", "Données compteur"))
        self.label_9.setText(_translate("Dialog", "Wh"))
        self.label_13.setText(_translate("Dialog", "Wh"))
        self.label_14.setText(_translate("Dialog", "Compteur h. creuses"))
        self.label_15.setText(_translate("Dialog", "Compteur h. pleines"))
        self.label_16.setText(_translate("Dialog", "Courant"))
        self.label_17.setText(_translate("Dialog", "Puissance. Apparente"))
        self.label_18.setText(_translate("Dialog", "A"))
        self.label_19.setText(_translate("Dialog", "VA"))
        self.label_34.setText(_translate("Dialog", "Tarif en cours"))
        self.label_35.setText(_translate("Dialog", "..."))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab2), _translate("Dialog", "EDF"))
        self.groupBox_4.setTitle(_translate("Dialog", "Vanne 3 voies régulation temperature"))
        self.label_25.setText(_translate("Dialog", "°C"))
        self.label_26.setText(_translate("Dialog", " T. sortie vanne "))
        self.progressBar_3.setFormat(_translate("Dialog", "%v %"))
        self.label_24.setText(_translate("Dialog", "Ouverture vanne"))
        self.label_21.setText(_translate("Dialog", "T. consigne eau"))
        self.label_20.setText(_translate("Dialog", "°C"))
        self.groupBox_5.setTitle(_translate("Dialog", "Chauffage electrique thermoplongeur"))
        self.label_22.setText(_translate("Dialog", "°C"))
        self.label_23.setText(_translate("Dialog", " T. cuve milieu"))
        self.label_12.setText(_translate("Dialog", "Puissance"))
        self.progressBar_2.setFormat(_translate("Dialog", "%v W"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab3), _translate("Dialog", "Regulation"))
        self.groupBox_9.setTitle(_translate("Dialog", "Resultats"))
        self.label_56.setText(_translate("Dialog", "Energie/J"))
        self.label_58.setText(_translate("Dialog", "kWh"))
        self.label_52.setText(_translate("Dialog", "kW"))
        self.label_50.setText(_translate("Dialog", "Puissance"))
        self.groupBox_6.setTitle(_translate("Dialog", "Temp. ballon"))
        self.label_38.setText(_translate("Dialog", "Millieu"))
        self.label_39.setText(_translate("Dialog", "Bas"))
        self.label_41.setText(_translate("Dialog", "°C"))
        self.label_42.setText(_translate("Dialog", "°C"))
        self.label_43.setText(_translate("Dialog", "°C"))
        self.label_44.setText(_translate("Dialog", "Haut"))
        self.groupBox_8.setTitle(_translate("Dialog", "Fonctionnement"))
        self.label_54.setText(_translate("Dialog", "l/h"))
        self.label_55.setText(_translate("Dialog", "Débit"))
        self.label_57.setText(_translate("Dialog", "Circulateur"))
        self.groupBox_7.setTitle(_translate("Dialog", "Temp. circuit solaire"))
        self.label_40.setText(_translate("Dialog", "Départ"))
        self.label_45.setText(_translate("Dialog", "Retour"))
        self.label_46.setText(_translate("Dialog", "°C"))
        self.label_47.setText(_translate("Dialog", "°C"))
        self.label_48.setText(_translate("Dialog", "°C"))
        self.label_49.setText(_translate("Dialog", "Capteurs"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab4), _translate("Dialog", "Solaire"))
        self.label_28.setText(_translate("Dialog", "Etat : "))
        self.label_29.setText(_translate("Dialog", "<html><head/><body><p><span style=\" color:#0000ff;\">Attente connexion serveurM QTT</span></p></body></html>"))
        self.pushButton_quit.setText(_translate("Dialog", "Quitter"))
        self.label_60.setText(_translate("Dialog", "Lecture Chauffage"))
        self.label_61.setText(_translate("Dialog", "Lecture Solaire"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())

